### ISSUE TITLE
train.py:L18 imports Models.CSCDeepLabv3P.DeepLabv3p, but Models/CSCDeepLabv3P.py doesn't have DeepLabv3p implementation

### ISSUE THREAD

**Issue by hiyuh** [NZWANG/CSC-Unet#1]
SSIA

**Comment by httang1224** [comment]
实验探索过程中设计的一些模型变体，注释该行即可。

**Comment by hiyuh** [comment]
> Some model variants designed during the experimental exploration, commenting the line is sufficient.

yes for just running `cfg.py` as is.
but no for reproducibility, comment out is a remedy.
it's not able to reproduce TABLE 8. results in your IEEE paper, since DeepLabv3+ is missing.

my intention is not to ask to publish your code.
it's just my 2 cents.
please feel free to close this issue, if you don't mind it.

**Comment by httang1224** [comment]
When the unfolding number is zero, CSCDeepLabv3+ is equivalent to DeepLabv3+, as explicitly discussed in the original paper. Therefore, you can simply set this value to obtain the DeepLabv3+ model.

**Comment by hiyuh** [comment]
> When the unfolding number is zero, CSCDeepLabv3+ is equivalent to DeepLabv3+, as explicitly discussed ...

ah my bad, you're right.
i'll close this issue.
